--2
SELECT * FROM CHUONGTRINH;
SELECT * FROM DIEM;
SELECT * FROM HOCVIEN;
SELECT * FROM KHOAHOC;
SELECT * FROM LOAILOP;
SELECT * FROM LOP;
SELECT * FROM MONHOC;
SELECT * FROM PHIEUTHU;
--3
SELECT *
FROM HOCVIEN
WHERE GIOITINH='1'; 
--4
SELECT *
FROM HOCVIEN
WHERE DIACHI LIKE '%C?n Th?%';
--5
SELECT *
FROM LOP
WHERE MAKH='K001';
--6
SELECT H.MAHV, TENHV
FROM HOCVIEN H JOIN PHIEUTHU P ON H.MAHV=P.MAHV
                JOIN LOP L ON L.MALOP=P.MALOP
                JOIN KHOAHOC K ON K.MAKH=L.MAKH
WHERE LOWER(TENKH)='khóa 1';
--7
SELECT TENHV
FROM HOCVIEN
WHERE TENHV LIKE '??%';
--8
SELECT *
FROM HOCVIEN
WHERE NGAYSINH LIKE '2000%';
--9
SELECT *
FROM HOCVIEN
WHERE NGAYSINH LIKE '2001-12%';
--10
SELECT *
FROM HOCVIEN
WHERE EXTRACT (YEAR FROM NGAYSINH) BETWEEN 1998 AND 2000;
--11
SELECT H.*
FROM HOCVIEN H
      JOIN PHIEUTHU P ON H.MAHV=P.MAHV
      JOIN LOP L ON P.MALOP=L.MALOP
      JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
WHERE LOWER(TENLOP)='l?p 1' AND
      LOWER(TENLOAI)='ti?ng anh c?n b?n';
--12
SELECT L.*
FROM LOP L JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
            JOIN CHUONGTRINH CT ON LL.MACT=CT.MACT
WHERE LOWER(TENCT)='ti?ng anh t?ng quát';
--13
SELECT P.*
FROM PHIEUTHU P JOIN LOP L ON P.MALOP=L.MALOP
                JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
WHERE LOWER(TENLOP)='l?p 1' AND
      LOWER(TENLOAI)='ti?ng anh a1';
--14
SELECT H.TENHV, MH.TENMH, D.DIEM
FROM HOCVIEN H JOIN PHIEUTHU P ON H.MAHV=P.MAHV
               JOIN LOP L ON P.MALOP=L.MALOP
               JOIN KHOAHOC K ON L.MAKH=K.MAKH
               JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
               JOIN DIEM D ON L.MALOP=D.MALOP
               JOIN MONHOC MH ON D.MAMH=MH.MAMH
WHERE LOWER(TENKH)='khóa 1';
--15
SELECT COUNT(*) SOHOCVIEN
FROM HOCVIEN;
--16
SELECT COUNT(*) SOHOCVIEN_LOP1
FROM HOCVIEN H
      JOIN PHIEUTHU P ON H.MAHV=P.MAHV
      JOIN LOP L ON P.MALOP=L.MALOP
      JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
WHERE LOWER(TENLOP)='l?p 1' AND
      LOWER(TENLOAI)='ti?ng anh c?n b?n';
--17
SELECT SUM(THANHTIEN) TONGSOTIEN
FROM  PHIEUTHU P JOIN LOP L ON P.MALOP=L.MALOP
      JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
WHERE LOWER(TENLOP)='l?p 3' AND
      LOWER(TENLOAI)='ti?ng anh a1';
--18
SELECT SUM(THANHTIEN) TONGSOTIEN
FROM KHOAHOC K JOIN LOP L ON K.MAKH=L.MAKH
              JOIN PHIEUTHU P ON L.MALOP=P.MALOP
WHERE LOWER(TENKH)='khóa 1';
--19
SELECT AVG(DIEM) DIEMTRUNGBINH
FROM DIEM D JOIN HOCVIEN H ON D.MAHV=H.MAHV
            JOIN LOP L ON D.MALOP=L.MALOP
            JOIN LOAILOP LL ON L.MALOAI=LL.MALOAI
WHERE LOWER(TENHV)='?? gia b?o'AND NGAYSINH='2001-12-02' AND LOWER(TENLOP)='l?p 1' AND LOWER(TENLOAI)='ti?ng anh c?n b?n';
--20
SELECT MAX(DIEM) DIEMLONNHAT
FROM DIEM;